Building DAG of jobs...
Using shell: /bin/bash
Provided cores: 24
Rules claiming more threads will be scaled down.
Job stats:
job                         count
------------------------  -------
plot_gbt_meerkat_spectra        6
plot_gbt_vs_meerkat_flux        1
tex2pdf_with_bib                1
total                           8

Resources before job selection: {'_cores': 24, '_nodes': 9223372036854775807}
Ready jobs (6)
Select jobs to execute...
Selected jobs (6)
Resources after job selection: {'_cores': 18, '_nodes': 9223372036854775801}

[Fri Oct 25 10:20:36 2024]
rule plot_gbt_meerkat_spectra:
    input: outputs/data/hcg16/hcg16_line60_masked.pb_corr_vopt.fits
    output: outputs/data/hcg16/hcg16_line60_masked.pb_corr_vopt_times_beam_factor_integrated_spec.txt, outputs/publication/figures/hcg16_meerkat_gbt_spec.pdf
    log: outputs/sofia/logs/hcg16/hcg16_meerkat_gbt_spec.log
    jobid: 8
    reason: Missing output files: outputs/publication/figures/hcg16_meerkat_gbt_spec.pdf, outputs/data/hcg16/hcg16_line60_masked.pb_corr_vopt_times_beam_factor_integrated_spec.txt
    wildcards: gal_idx=hcg16
    priority: 98
    resources: mem_mb=1069, mem_mib=1020, disk_mb=1069, disk_mib=1020, tmpdir=/data


[Fri Oct 25 10:20:36 2024]
rule plot_gbt_meerkat_spectra:
    input: outputs/data/hcg31/hcg31_line60_masked.pb_corr_vopt.fits
    output: outputs/data/hcg31/hcg31_line60_masked.pb_corr_vopt_times_beam_factor_integrated_spec.txt, outputs/publication/figures/hcg31_meerkat_gbt_spec.pdf
    log: outputs/sofia/logs/hcg31/hcg31_meerkat_gbt_spec.log
    jobid: 10
    reason: Missing output files: outputs/data/hcg31/hcg31_line60_masked.pb_corr_vopt_times_beam_factor_integrated_spec.txt, outputs/publication/figures/hcg31_meerkat_gbt_spec.pdf
    wildcards: gal_idx=hcg31
    priority: 98
    resources: mem_mb=1890, mem_mib=1803, disk_mb=1890, disk_mib=1803, tmpdir=/data


[Fri Oct 25 10:20:36 2024]
rule plot_gbt_meerkat_spectra:
    input: outputs/data/hcg91/hcg91_line60_masked.pb_corr_vopt.fits
    output: outputs/data/hcg91/hcg91_line60_masked.pb_corr_vopt_times_beam_factor_integrated_spec.txt, outputs/publication/figures/hcg91_meerkat_gbt_spec.pdf
    log: outputs/sofia/logs/hcg91/hcg91_meerkat_gbt_spec.log
    jobid: 12
    reason: Missing output files: outputs/publication/figures/hcg91_meerkat_gbt_spec.pdf, outputs/data/hcg91/hcg91_line60_masked.pb_corr_vopt_times_beam_factor_integrated_spec.txt
    wildcards: gal_idx=hcg91
    priority: 98
    resources: mem_mb=3313, mem_mib=3160, disk_mb=3313, disk_mib=3160, tmpdir=/data


[Fri Oct 25 10:20:36 2024]
rule plot_gbt_meerkat_spectra:
    input: outputs/data/hcg30/hcg30_line60_masked.pb_corr_vopt.fits
    output: outputs/data/hcg30/hcg30_line60_masked.pb_corr_vopt_times_beam_factor_integrated_spec.txt, outputs/publication/figures/hcg30_meerkat_gbt_spec.pdf
    log: outputs/sofia/logs/hcg30/hcg30_meerkat_gbt_spec.log
    jobid: 9
    reason: Missing output files: outputs/data/hcg30/hcg30_line60_masked.pb_corr_vopt_times_beam_factor_integrated_spec.txt, outputs/publication/figures/hcg30_meerkat_gbt_spec.pdf
    wildcards: gal_idx=hcg30
    priority: 98
    resources: mem_mb=1203, mem_mib=1148, disk_mb=1203, disk_mib=1148, tmpdir=/data


[Fri Oct 25 10:20:36 2024]
rule plot_gbt_meerkat_spectra:
    input: outputs/data/hcg90/hcg90_line60_masked.pb_corr_vopt.fits
    output: outputs/data/hcg90/hcg90_line60_masked.pb_corr_vopt_times_beam_factor_integrated_spec.txt, outputs/publication/figures/hcg90_meerkat_gbt_spec.pdf
    log: outputs/sofia/logs/hcg90/hcg90_meerkat_gbt_spec.log
    jobid: 11
    reason: Missing output files: outputs/data/hcg90/hcg90_line60_masked.pb_corr_vopt_times_beam_factor_integrated_spec.txt, outputs/publication/figures/hcg90_meerkat_gbt_spec.pdf
    wildcards: gal_idx=hcg90
    priority: 98
    resources: mem_mb=2206, mem_mib=2104, disk_mb=2206, disk_mib=2104, tmpdir=/data


[Fri Oct 25 10:20:36 2024]
rule plot_gbt_meerkat_spectra:
    input: outputs/data/hcg97/hcg97_line60_masked.pb_corr_vopt.fits
    output: outputs/data/hcg97/hcg97_line60_masked.pb_corr_vopt_times_beam_factor_integrated_spec.txt, outputs/publication/figures/hcg97_meerkat_gbt_spec.pdf
    log: outputs/sofia/logs/hcg97/hcg97_meerkat_gbt_spec.log
    jobid: 13
    reason: Missing output files: outputs/publication/figures/hcg97_meerkat_gbt_spec.pdf, outputs/data/hcg97/hcg97_line60_masked.pb_corr_vopt_times_beam_factor_integrated_spec.txt
    wildcards: gal_idx=hcg97
    priority: 98
    resources: mem_mb=1439, mem_mib=1373, disk_mb=1439, disk_mib=1373, tmpdir=/data

Full Traceback (most recent call last):
  File "/opt/conda_envs/snakemake/lib/python3.10/site-packages/snakemake/executors/__init__.py", line 2656, in run_wrapper
    run(
  File "/data/workflow/rules/plot_gbt_meerkat_spectra.smk", line 56, in __rule_plot_gbt_meerkat_spectra
  File "/opt/conda_envs/snakemake/lib/python3.10/site-packages/snakemake/shell.py", line 294, in __new__
    raise sp.CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'set -euo pipefail;  python workflow/scripts/plot_gbt_meerkat_spectra.py --cube outputs/data/hcg16/hcg16_line60_masked.pb_corr_vopt.fits' returned non-zero exit status 1.

[Fri Oct 25 10:20:45 2024]
Error in rule plot_gbt_meerkat_spectra:
    jobid: 8
    input: outputs/data/hcg16/hcg16_line60_masked.pb_corr_vopt.fits
    output: outputs/data/hcg16/hcg16_line60_masked.pb_corr_vopt_times_beam_factor_integrated_spec.txt, outputs/publication/figures/hcg16_meerkat_gbt_spec.pdf
    log: outputs/sofia/logs/hcg16/hcg16_meerkat_gbt_spec.log (check log file(s) for error details)
    shell:
        python workflow/scripts/plot_gbt_meerkat_spectra.py --cube outputs/data/hcg16/hcg16_line60_masked.pb_corr_vopt.fits
        (one of the commands exited with non-zero exit code; note that snakemake uses bash strict mode!)

Full Traceback (most recent call last):
  File "/opt/conda_envs/snakemake/lib/python3.10/site-packages/snakemake/executors/__init__.py", line 2656, in run_wrapper
    run(
  File "/data/workflow/rules/plot_gbt_meerkat_spectra.smk", line 56, in __rule_plot_gbt_meerkat_spectra
  File "/opt/conda_envs/snakemake/lib/python3.10/site-packages/snakemake/shell.py", line 294, in __new__
    raise sp.CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'set -euo pipefail;  python workflow/scripts/plot_gbt_meerkat_spectra.py --cube outputs/data/hcg16/hcg16_line60_masked.pb_corr_vopt.fits' returned non-zero exit status 1.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/conda_envs/snakemake/lib/python3.10/site-packages/snakemake/executors/__init__.py", line 715, in _callback
    raise ex
  File "/opt/conda_envs/snakemake/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/opt/conda_envs/snakemake/lib/python3.10/site-packages/snakemake/executors/__init__.py", line 699, in cached_or_run
    run_func(*args)
  File "/opt/conda_envs/snakemake/lib/python3.10/site-packages/snakemake/executors/__init__.py", line 2692, in run_wrapper
    raise RuleException(
snakemake.exceptions.RuleException: CalledProcessError in file /data/workflow/rules/plot_gbt_meerkat_spectra.smk, line 39:
Command 'set -euo pipefail;  python workflow/scripts/plot_gbt_meerkat_spectra.py --cube outputs/data/hcg16/hcg16_line60_masked.pb_corr_vopt.fits' returned non-zero exit status 1.
  File "/data/workflow/rules/plot_gbt_meerkat_spectra.smk", line 39, in __rule_plot_gbt_meerkat_spectra

RuleException:
CalledProcessError in file /data/workflow/rules/plot_gbt_meerkat_spectra.smk, line 39:
Command 'set -euo pipefail;  python workflow/scripts/plot_gbt_meerkat_spectra.py --cube outputs/data/hcg16/hcg16_line60_masked.pb_corr_vopt.fits' returned non-zero exit status 1.
  File "/data/workflow/rules/plot_gbt_meerkat_spectra.smk", line 39, in __rule_plot_gbt_meerkat_spectra
  File "/opt/conda_envs/snakemake/lib/python3.10/concurrent/futures/thread.py", line 58, in run
Full Traceback (most recent call last):
  File "/opt/conda_envs/snakemake/lib/python3.10/site-packages/snakemake/executors/__init__.py", line 2656, in run_wrapper
    run(
  File "/data/workflow/rules/plot_gbt_meerkat_spectra.smk", line 56, in __rule_plot_gbt_meerkat_spectra
  File "/opt/conda_envs/snakemake/lib/python3.10/site-packages/snakemake/shell.py", line 294, in __new__
    raise sp.CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'set -euo pipefail;  python workflow/scripts/plot_gbt_meerkat_spectra.py --cube outputs/data/hcg30/hcg30_line60_masked.pb_corr_vopt.fits' returned non-zero exit status 1.

[Fri Oct 25 10:20:47 2024]
Error in rule plot_gbt_meerkat_spectra:
    jobid: 9
    input: outputs/data/hcg30/hcg30_line60_masked.pb_corr_vopt.fits
    output: outputs/data/hcg30/hcg30_line60_masked.pb_corr_vopt_times_beam_factor_integrated_spec.txt, outputs/publication/figures/hcg30_meerkat_gbt_spec.pdf
    log: outputs/sofia/logs/hcg30/hcg30_meerkat_gbt_spec.log (check log file(s) for error details)
    shell:
        python workflow/scripts/plot_gbt_meerkat_spectra.py --cube outputs/data/hcg30/hcg30_line60_masked.pb_corr_vopt.fits
        (one of the commands exited with non-zero exit code; note that snakemake uses bash strict mode!)

Full Traceback (most recent call last):
  File "/opt/conda_envs/snakemake/lib/python3.10/site-packages/snakemake/executors/__init__.py", line 2656, in run_wrapper
    run(
  File "/data/workflow/rules/plot_gbt_meerkat_spectra.smk", line 56, in __rule_plot_gbt_meerkat_spectra
  File "/opt/conda_envs/snakemake/lib/python3.10/site-packages/snakemake/shell.py", line 294, in __new__
    raise sp.CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'set -euo pipefail;  python workflow/scripts/plot_gbt_meerkat_spectra.py --cube outputs/data/hcg30/hcg30_line60_masked.pb_corr_vopt.fits' returned non-zero exit status 1.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/conda_envs/snakemake/lib/python3.10/site-packages/snakemake/executors/__init__.py", line 715, in _callback
    raise ex
  File "/opt/conda_envs/snakemake/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/opt/conda_envs/snakemake/lib/python3.10/site-packages/snakemake/executors/__init__.py", line 699, in cached_or_run
    run_func(*args)
  File "/opt/conda_envs/snakemake/lib/python3.10/site-packages/snakemake/executors/__init__.py", line 2692, in run_wrapper
    raise RuleException(
snakemake.exceptions.RuleException: CalledProcessError in file /data/workflow/rules/plot_gbt_meerkat_spectra.smk, line 39:
Command 'set -euo pipefail;  python workflow/scripts/plot_gbt_meerkat_spectra.py --cube outputs/data/hcg30/hcg30_line60_masked.pb_corr_vopt.fits' returned non-zero exit status 1.
  File "/data/workflow/rules/plot_gbt_meerkat_spectra.smk", line 39, in __rule_plot_gbt_meerkat_spectra

RuleException:
CalledProcessError in file /data/workflow/rules/plot_gbt_meerkat_spectra.smk, line 39:
Command 'set -euo pipefail;  python workflow/scripts/plot_gbt_meerkat_spectra.py --cube outputs/data/hcg30/hcg30_line60_masked.pb_corr_vopt.fits' returned non-zero exit status 1.
  File "/data/workflow/rules/plot_gbt_meerkat_spectra.smk", line 39, in __rule_plot_gbt_meerkat_spectra
  File "/opt/conda_envs/snakemake/lib/python3.10/concurrent/futures/thread.py", line 58, in run
Full Traceback (most recent call last):
  File "/opt/conda_envs/snakemake/lib/python3.10/site-packages/snakemake/executors/__init__.py", line 2656, in run_wrapper
    run(
  File "/data/workflow/rules/plot_gbt_meerkat_spectra.smk", line 56, in __rule_plot_gbt_meerkat_spectra
  File "/opt/conda_envs/snakemake/lib/python3.10/site-packages/snakemake/shell.py", line 294, in __new__
    raise sp.CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'set -euo pipefail;  python workflow/scripts/plot_gbt_meerkat_spectra.py --cube outputs/data/hcg31/hcg31_line60_masked.pb_corr_vopt.fits' returned non-zero exit status 1.

[Fri Oct 25 10:20:48 2024]
Error in rule plot_gbt_meerkat_spectra:
    jobid: 10
    input: outputs/data/hcg31/hcg31_line60_masked.pb_corr_vopt.fits
    output: outputs/data/hcg31/hcg31_line60_masked.pb_corr_vopt_times_beam_factor_integrated_spec.txt, outputs/publication/figures/hcg31_meerkat_gbt_spec.pdf
    log: outputs/sofia/logs/hcg31/hcg31_meerkat_gbt_spec.log (check log file(s) for error details)
    shell:
        python workflow/scripts/plot_gbt_meerkat_spectra.py --cube outputs/data/hcg31/hcg31_line60_masked.pb_corr_vopt.fits
        (one of the commands exited with non-zero exit code; note that snakemake uses bash strict mode!)

Full Traceback (most recent call last):
  File "/opt/conda_envs/snakemake/lib/python3.10/site-packages/snakemake/executors/__init__.py", line 2656, in run_wrapper
    run(
  File "/data/workflow/rules/plot_gbt_meerkat_spectra.smk", line 56, in __rule_plot_gbt_meerkat_spectra
  File "/opt/conda_envs/snakemake/lib/python3.10/site-packages/snakemake/shell.py", line 294, in __new__
    raise sp.CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'set -euo pipefail;  python workflow/scripts/plot_gbt_meerkat_spectra.py --cube outputs/data/hcg31/hcg31_line60_masked.pb_corr_vopt.fits' returned non-zero exit status 1.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/conda_envs/snakemake/lib/python3.10/site-packages/snakemake/executors/__init__.py", line 715, in _callback
    raise ex
  File "/opt/conda_envs/snakemake/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/opt/conda_envs/snakemake/lib/python3.10/site-packages/snakemake/executors/__init__.py", line 699, in cached_or_run
    run_func(*args)
  File "/opt/conda_envs/snakemake/lib/python3.10/site-packages/snakemake/executors/__init__.py", line 2692, in run_wrapper
    raise RuleException(
snakemake.exceptions.RuleException: CalledProcessError in file /data/workflow/rules/plot_gbt_meerkat_spectra.smk, line 39:
Command 'set -euo pipefail;  python workflow/scripts/plot_gbt_meerkat_spectra.py --cube outputs/data/hcg31/hcg31_line60_masked.pb_corr_vopt.fits' returned non-zero exit status 1.
  File "/data/workflow/rules/plot_gbt_meerkat_spectra.smk", line 39, in __rule_plot_gbt_meerkat_spectra

RuleException:
CalledProcessError in file /data/workflow/rules/plot_gbt_meerkat_spectra.smk, line 39:
Command 'set -euo pipefail;  python workflow/scripts/plot_gbt_meerkat_spectra.py --cube outputs/data/hcg31/hcg31_line60_masked.pb_corr_vopt.fits' returned non-zero exit status 1.
  File "/data/workflow/rules/plot_gbt_meerkat_spectra.smk", line 39, in __rule_plot_gbt_meerkat_spectra
  File "/opt/conda_envs/snakemake/lib/python3.10/concurrent/futures/thread.py", line 58, in run
Full Traceback (most recent call last):
  File "/opt/conda_envs/snakemake/lib/python3.10/site-packages/snakemake/executors/__init__.py", line 2656, in run_wrapper
    run(
  File "/data/workflow/rules/plot_gbt_meerkat_spectra.smk", line 56, in __rule_plot_gbt_meerkat_spectra
  File "/opt/conda_envs/snakemake/lib/python3.10/site-packages/snakemake/shell.py", line 294, in __new__
    raise sp.CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'set -euo pipefail;  python workflow/scripts/plot_gbt_meerkat_spectra.py --cube outputs/data/hcg97/hcg97_line60_masked.pb_corr_vopt.fits' returned non-zero exit status 1.

[Fri Oct 25 10:20:48 2024]
Error in rule plot_gbt_meerkat_spectra:
    jobid: 13
    input: outputs/data/hcg97/hcg97_line60_masked.pb_corr_vopt.fits
    output: outputs/data/hcg97/hcg97_line60_masked.pb_corr_vopt_times_beam_factor_integrated_spec.txt, outputs/publication/figures/hcg97_meerkat_gbt_spec.pdf
    log: outputs/sofia/logs/hcg97/hcg97_meerkat_gbt_spec.log (check log file(s) for error details)
    shell:
        python workflow/scripts/plot_gbt_meerkat_spectra.py --cube outputs/data/hcg97/hcg97_line60_masked.pb_corr_vopt.fits
        (one of the commands exited with non-zero exit code; note that snakemake uses bash strict mode!)

Full Traceback (most recent call last):
  File "/opt/conda_envs/snakemake/lib/python3.10/site-packages/snakemake/executors/__init__.py", line 2656, in run_wrapper
    run(
  File "/data/workflow/rules/plot_gbt_meerkat_spectra.smk", line 56, in __rule_plot_gbt_meerkat_spectra
  File "/opt/conda_envs/snakemake/lib/python3.10/site-packages/snakemake/shell.py", line 294, in __new__
    raise sp.CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'set -euo pipefail;  python workflow/scripts/plot_gbt_meerkat_spectra.py --cube outputs/data/hcg97/hcg97_line60_masked.pb_corr_vopt.fits' returned non-zero exit status 1.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/conda_envs/snakemake/lib/python3.10/site-packages/snakemake/executors/__init__.py", line 715, in _callback
    raise ex
  File "/opt/conda_envs/snakemake/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/opt/conda_envs/snakemake/lib/python3.10/site-packages/snakemake/executors/__init__.py", line 699, in cached_or_run
    run_func(*args)
  File "/opt/conda_envs/snakemake/lib/python3.10/site-packages/snakemake/executors/__init__.py", line 2692, in run_wrapper
    raise RuleException(
snakemake.exceptions.RuleException: CalledProcessError in file /data/workflow/rules/plot_gbt_meerkat_spectra.smk, line 39:
Command 'set -euo pipefail;  python workflow/scripts/plot_gbt_meerkat_spectra.py --cube outputs/data/hcg97/hcg97_line60_masked.pb_corr_vopt.fits' returned non-zero exit status 1.
  File "/data/workflow/rules/plot_gbt_meerkat_spectra.smk", line 39, in __rule_plot_gbt_meerkat_spectra

RuleException:
CalledProcessError in file /data/workflow/rules/plot_gbt_meerkat_spectra.smk, line 39:
Command 'set -euo pipefail;  python workflow/scripts/plot_gbt_meerkat_spectra.py --cube outputs/data/hcg97/hcg97_line60_masked.pb_corr_vopt.fits' returned non-zero exit status 1.
  File "/data/workflow/rules/plot_gbt_meerkat_spectra.smk", line 39, in __rule_plot_gbt_meerkat_spectra
  File "/opt/conda_envs/snakemake/lib/python3.10/concurrent/futures/thread.py", line 58, in run
Full Traceback (most recent call last):
  File "/opt/conda_envs/snakemake/lib/python3.10/site-packages/snakemake/executors/__init__.py", line 2656, in run_wrapper
    run(
  File "/data/workflow/rules/plot_gbt_meerkat_spectra.smk", line 56, in __rule_plot_gbt_meerkat_spectra
  File "/opt/conda_envs/snakemake/lib/python3.10/site-packages/snakemake/shell.py", line 294, in __new__
    raise sp.CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'set -euo pipefail;  python workflow/scripts/plot_gbt_meerkat_spectra.py --cube outputs/data/hcg90/hcg90_line60_masked.pb_corr_vopt.fits' returned non-zero exit status 1.

[Fri Oct 25 10:20:49 2024]
Error in rule plot_gbt_meerkat_spectra:
    jobid: 11
    input: outputs/data/hcg90/hcg90_line60_masked.pb_corr_vopt.fits
    output: outputs/data/hcg90/hcg90_line60_masked.pb_corr_vopt_times_beam_factor_integrated_spec.txt, outputs/publication/figures/hcg90_meerkat_gbt_spec.pdf
    log: outputs/sofia/logs/hcg90/hcg90_meerkat_gbt_spec.log (check log file(s) for error details)
    shell:
        python workflow/scripts/plot_gbt_meerkat_spectra.py --cube outputs/data/hcg90/hcg90_line60_masked.pb_corr_vopt.fits
        (one of the commands exited with non-zero exit code; note that snakemake uses bash strict mode!)

Full Traceback (most recent call last):
  File "/opt/conda_envs/snakemake/lib/python3.10/site-packages/snakemake/executors/__init__.py", line 2656, in run_wrapper
    run(
  File "/data/workflow/rules/plot_gbt_meerkat_spectra.smk", line 56, in __rule_plot_gbt_meerkat_spectra
  File "/opt/conda_envs/snakemake/lib/python3.10/site-packages/snakemake/shell.py", line 294, in __new__
    raise sp.CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'set -euo pipefail;  python workflow/scripts/plot_gbt_meerkat_spectra.py --cube outputs/data/hcg90/hcg90_line60_masked.pb_corr_vopt.fits' returned non-zero exit status 1.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/conda_envs/snakemake/lib/python3.10/site-packages/snakemake/executors/__init__.py", line 715, in _callback
    raise ex
  File "/opt/conda_envs/snakemake/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/opt/conda_envs/snakemake/lib/python3.10/site-packages/snakemake/executors/__init__.py", line 699, in cached_or_run
    run_func(*args)
  File "/opt/conda_envs/snakemake/lib/python3.10/site-packages/snakemake/executors/__init__.py", line 2692, in run_wrapper
    raise RuleException(
snakemake.exceptions.RuleException: CalledProcessError in file /data/workflow/rules/plot_gbt_meerkat_spectra.smk, line 39:
Command 'set -euo pipefail;  python workflow/scripts/plot_gbt_meerkat_spectra.py --cube outputs/data/hcg90/hcg90_line60_masked.pb_corr_vopt.fits' returned non-zero exit status 1.
  File "/data/workflow/rules/plot_gbt_meerkat_spectra.smk", line 39, in __rule_plot_gbt_meerkat_spectra

RuleException:
CalledProcessError in file /data/workflow/rules/plot_gbt_meerkat_spectra.smk, line 39:
Command 'set -euo pipefail;  python workflow/scripts/plot_gbt_meerkat_spectra.py --cube outputs/data/hcg90/hcg90_line60_masked.pb_corr_vopt.fits' returned non-zero exit status 1.
  File "/data/workflow/rules/plot_gbt_meerkat_spectra.smk", line 39, in __rule_plot_gbt_meerkat_spectra
  File "/opt/conda_envs/snakemake/lib/python3.10/concurrent/futures/thread.py", line 58, in run
Terminating processes on user request, this might take some time.
